---
# file: tasks/ubuntu.yaml

- name: Ensure old versions of Polychromatic are not installed.
  package:
    name:
      - "{{ polychromatic_package }}"
    state: absent
  tags:
    - polychromatic-inst-dependencies

- name: Ensure dependencies are installed.
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - python3-apt
    state: present
  tags:
    - polychromatic-inst-dependencies

- name: Add polychromatic repository.
  apt_repository:
    repo: "{{ polychromatic_apt_url }}"
    state: "{{ polychromatic_apt_state }}"
    update_cache: true
  tags:
    - polychromatic-inst-dependencies
