---
# file: tasks/ubuntu.yaml

- name: Install Dependencies.
  ansible.builtin.apt:
    name: "{{ packages | flatten(levels=1) }}"
    state: "present"
    cache_valid_time: 3600
    install_recommends: false
  tags:
    - polychromatic-inst-dependencies

- name: Add Polychromatic Repository.
  ansible.builtin.apt_repository:
    repo: "{{ polychromatic_apt_url }}"
    state: "{{ polychromatic_apt_state }}"
    update_cache: true
  tags:
    - polychromatic-conf-apt
