---
# file: tasks/ubuntu.yaml

- name: Ensure dependencies are installed.
  apt:
    name:
      - "apt-transport-https"
      - "ca-certificates"
      - "python3-apt"
    state: "present"
    cache_valid_time: 3600
    install_recommends: False
  tags:
    - polychromatic-inst-dependencies

- name: Add polychromatic repository.
  apt_repository:
    repo: "{{ polychromatic_apt_url }}"
    state: "{{ polychromatic_apt_state }}"
    update_cache: true
  tags:
    - polychromatic-conf-apt
