---
# file: molecule/default/molecule.yml

dependency:
  name: galaxy
  options:
    # Put roles right to this one. Reduce possible role locations.
    roles-path: ../pmikus.polychromatic/molecule/default/roles
driver:
  name: docker
lint: |
  yamllint .
platforms:
  - name: ${DISTRO:-ubuntu-20.04}
    image: "pmikus/docker-${MOLECULE_DISTRO:-ubuntu-20.04}-ansible:latest"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
