# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 6
      matrix:
        IMAGE: [ubuntu-20.10, ubuntu-20.04, ubuntu-18.04]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout source code
      uses: actions/checkout@v1
      with:
        path: 'pmikus.ansible-role-openrazer'

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Update repo cache, install python3-setuptools and required pip modules
      run: |
        sudo apt-get update
        sudo apt-get install python3-setuptools -y
        pip3 install -U pip wheel ansible molecule[docker] docker ansible-lint flake8 pytest-testinfra
    - name: Execute Molecule test of role for ${{ matrix.IMAGE }}
      run: DISTRO=${{ matrix.IMAGE }} molecule test
      env:
        PY_COLORS: '1'
        ANSIBLE_FORCE_COLOR: '1'

  code_quality:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout source code
      uses: actions/checkout@v1
      with:
        path: 'pmikus.ansible-role-openrazer'
        fetch-depth: 0

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      with:
        args: >
          -Dsonar.projectVersion=${{ github.ref }}_${{ github.run_number }}
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
